app/vrconf/forms.py
from flask.ext.wtf import Form
from wtforms import StringField, BooleanField, SubmitField, IntegerField, SelectField, HiddenField
from wtforms.validators import Required

class ConnectionSettingsForm(Form):
    own_twittername = StringField('twittername (e.g. @jondoe)', validators=[Required()])
    consumer_key = StringField('consumer_key', validators=[Required()])
    consumer_secret = StringField('consumer_secret', validators=[Required()])
    access_token = StringField('access_token', validators=[Required()])
    access_token_secret = StringField('access_token_secret', validators=[Required()])
    submit = SubmitField('Submit Information')

class AdvancedSettingsForm(Form):
    max_updates_per_day = IntegerField('maximum number updates per day')
    status_update_score = IntegerField('status update score')
    follow_score = IntegerField('follow score')
    retweet_score = IntegerField('retweet score')
    favorite_score = IntegerField('favorite score')
    number_active_favorites = IntegerField('number active favorites')
    number_active_retweets = IntegerField('number active retweets')
    number_active_follows = IntegerField('number active follows')
    only_with_url = BooleanField('only act on tweets with url')
    submit = SubmitField('Submit Information')

class KeywordForm(Form):
    keyword = StringField()
    weight = SelectField(choices=[('5', '5'), ('7', '7'), ('12', '12')])
    submit = SubmitField('Add Item')

class BlacklistKeywordForm(Form):
    keyword = StringField()
    weight = SelectField( choices=[('-5', ' minus 5'), ('-7', ' minus 7'), ('-12','minus 12'), ('-1000', 'forbidden')])
    submit = SubmitField('Add Item')

class NeverUnfollowForm(Form):
    account_name = StringField()
    submit = SubmitField('Add Item')

class OnOffForm(Form):
    #onoff = SelectField(choices=[('0', 'off'), ('1', 'on')])
    onoff = HiddenField()
    submit = SubmitField('Update Status')

app/vrconf/__init__.py
from flask import Blueprint

vrconf = Blueprint('vrconf', __name__)

from . import views

app/vrconf/views.py
from flask import render_template, redirect, request, url_for, flash
from flask.ext.login import login_user, logout_user, login_required, \
    current_user


from . import vrconf
from .. import db
from ..models import GeneralSettings, WhiteList, BlackList,NeverUnfollowAccounts, User
from .forms import ConnectionSettingsForm, AdvancedSettingsForm, KeywordForm, BlacklistKeywordForm, NeverUnfollowForm, \
    OnOffForm

#ToDo write button with which connection to TWitter can be tested

@vrconf.route('/connection_settings', methods=['GET', 'POST'])
@login_required
def connection_settings():
    form = ConnectionSettingsForm()
    if form.validate_on_submit():
        sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
        if sett is None:
            # This is the case when the user logs in for the first time
            sett = GeneralSettings(
                fk_user_id = current_user.id,
                consumer_key=form.consumer_key.data,
                consumer_secret=form.consumer_secret.data,
                access_token=form.access_token.data,
                access_token_secret = form.access_token_secret.data,
                own_twittername=form.own_twittername.data.lstrip('@'))
            flash('Your Connection Settings have been stored')
            current_user.connection_settings_set = True
            db.session.add(current_user)
            db.session.add(sett)
            db.session.commit()
            return redirect(url_for('main.index'))
        else:
            sett.own_twittername = form.own_twittername.data
            sett.consumer_key = form.consumer_key.data
            sett.consumer_secret = form.consumer_secret.data
            sett.access_token = form.access_token.data
            sett.access_token_secret = form.access_token_secret.data
            #ToDo change the below line such that this is set true when connection settings are tested successfully
            current_user.connection_settings_set = True
            db.session.add(current_user)
            db.session.add(sett)
            db.session.commit()
            flash('Your Connection Settings have been changed')
            return redirect(url_for('main.index'))
    sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
    if not sett is None:
        form.own_twittername.data = sett.own_twittername
        form.access_token.data = sett.access_token
        form.access_token_secret.data = sett.access_token_secret
        form.consumer_key.data = sett.consumer_key
        form.consumer_secret.data = sett.consumer_secret
    return render_template('vrconf/connection_settings.html', form=form)


def set_restart_needed_flag():
    """set the restart_needed flag to 1"""
    sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
    sett.restart_needed = 1
    db.session.add(sett)
    db.session.commit()


@vrconf.route('/advanced_settings', methods=['GET', 'POST'])
@login_required
def advanced_settings():
    form = AdvancedSettingsForm()
    if form.validate_on_submit():
        sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
        sett.max_updates_per_day = form.max_updates_per_day.data
        sett.status_update_score = form.status_update_score.data
        sett.follow_score = form.follow_score.data
        sett.retweet_score = form.retweet_score.data
        sett.favorite_score = form.favorite_score.data
        sett.only_with_url = form.only_with_url.data
        sett.number_active_follows = form.number_active_follows.data
        sett.number_active_retweets = form.number_active_retweets.data
        sett.number_active_favorites = form.number_active_favorites.data
        sett.restart_needed = 1
        db.session.commit()
        flash('Your Advanced Settings have been stored')
        return redirect(url_for('main.index'))
    sett2 = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
    if sett2 is None:
            flash('Please enter your settings information first')
            return redirect(url_for('vrconf.connection_settings'))
    form.max_updates_per_day.data = sett2.max_updates_per_day
    form.only_with_url.data = sett2.only_with_url
    form.favorite_score.data = sett2.favorite_score
    form.follow_score.data = sett2.follow_score
    form.status_update_score.data = sett2.status_update_score
    form.number_active_favorites.data = sett2.number_active_favorites
    form.number_active_follows.data = sett2.number_active_follows
    form.number_active_retweets.data = sett2.number_active_retweets
    form.follow_score.data = sett2.follow_score
    form.retweet_score.data = sett2.retweet_score
    return render_template('vrconf/advanced_settings.html', form=form)

@vrconf.route('/target_settings', methods=['GET', 'POST'])
@login_required
def target_settings():
    form = KeywordForm()
    if form.validate_on_submit():
        kwd = WhiteList(
            fk_user_id=current_user.id,
            keyword=form.keyword.data,
            weight=form.weight.data)
        set_restart_needed_flag()
        db.session.add(kwd)
        db.session.commit()
    kwds = WhiteList.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/target_settings.html', form=form, entries=kwds)

@vrconf.route('/update_entry', methods=['GET', 'POST'])
@login_required
def update_entry():
    form = KeywordForm()
    del_id = request.form['id_to_delete']
    kwd = request.form['keyword']
    weight = request.form['weight']
    del_keyword = WhiteList.query.filter_by(id=del_id).first()
    set_restart_needed_flag()
    db.session.delete(del_keyword)
    db.session.commit()
    if 'change' in request.form:
        form.keyword.data = kwd
        form.weight.data = weight
    kwds = WhiteList.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/target_settings.html', form = form, entries=kwds)

@vrconf.route('/blacklist_settings', methods=['GET', 'POST'])
@login_required
def blacklist_settings():
    form = BlacklistKeywordForm()
    if form.validate_on_submit():
        kwd = BlackList(
            fk_user_id = current_user.id,
            keyword = form.keyword.data,
            weight = form.weight.data)
        set_restart_needed_flag()
        db.session.add(kwd)
        db.session.commit()
    kwds = BlackList.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/blacklist_settings.html', form2=form, entries=kwds)

@vrconf.route('/update_blacklist_entry', methods=['GET', 'POST'])
@login_required
def update_blacklist_entry():
    form = BlacklistKeywordForm()
    del_id = request.form['id_to_delete']
    kwd = request.form['keyword']
    weight = request.form['weight']
    del_keyword = BlackList.query.filter_by(id=del_id).first()
    set_restart_needed_flag()
    db.session.delete(del_keyword)
    db.session.commit()
    if 'change' in request.form:
        form.keyword.data = kwd
        form.weight.data = weight
    kwds = BlackList.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/blacklist_settings.html', form2 = form, entries=kwds)


@vrconf.route('/never_unfollow_settings', methods=['GET', 'POST'])
@login_required
def never_unfollow_settings():
    form = NeverUnfollowForm()
    if form.validate_on_submit():
        account = NeverUnfollowAccounts(
            fk_user_id=current_user.id,
            accountname=form.account_name.data.lstrip('@')
        )
        set_restart_needed_flag()
        db.session.add(account)
        db.session.commit()
    accounts = NeverUnfollowAccounts.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/account_never_unfollow_settings.html', form=form, entries=accounts)


@vrconf.route('/update_neverunfollow_entry', methods=['GET', 'POST'])
@login_required
def update_neverunfollow_entry():
    form = NeverUnfollowForm()
    del_id = request.form['id_to_delete']
    account_name = request.form['account_name']
    del_account = NeverUnfollowAccounts.query.filter_by(id=del_id).first()
    set_restart_needed_flag()
    db.session.delete(del_account)
    db.session.commit()
    if 'change' in request.form:
        form.account_name.data = '@'+account_name
    accounts = NeverUnfollowAccounts.query.filter_by(fk_user_id=current_user.id).all()
    return render_template('vrconf/account_never_unfollow_settings.html', form=form, entries=accounts)


@vrconf.route('/delete_account', methods=['GET', 'POST'])
@login_required
def delete_account():
    return render_template('vrconf/delete_account.html')

@vrconf.route('/yes_delete', methods=['GET', 'POST'])
@login_required
def yes_delete():
    flash('Your account has been deleted')
    accounts = NeverUnfollowAccounts.query.filter_by(fk_user_id=current_user.id).all()
    b_kwds = BlackList.query.filter_by(fk_user_id=current_user.id).all()
    w_kwds = WhiteList.query.filter_by(fk_user_id=current_user.id).all()
    sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
    user =User.query.filter_by(id=current_user.id).first()
    for account in accounts:
        db.session.delete(account)
    for kwd in b_kwds:
        db.session.delete(kwd)
    for kwd in w_kwds:
        db.session.delete(kwd)
    if sett is not None:
        db.session.delete(sett)
    db.session.delete(user)
    db.session.commit()

    return redirect(url_for('main.index'))

@vrconf.route('/onoff', methods=['GET', 'POST'])
@login_required
def onoff():
    form = OnOffForm()
    if form.validate_on_submit():
        sett = GeneralSettings.query.filter_by(fk_user_id=current_user.id).first()
        sett.onoff = 0 if sett.onoff == 1 else 1
        db.session.add(sett)
        db.session.commit()
    return redirect(url_for('main.index'))

app/templates/vrconf/account_never_unfollow_settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Valureach - Accounts that should never be unfollowed{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Enter Accounts that should never be unfollowed</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form=form, action=url_for('vrconf.never_unfollow_settings'))}}
</div>


<div class = "container">
<div class="col-md-12">
    <h1>Account Never Unfollow List</h1>
    {% if entries|length > 0 %}
    <ul class= "list-group">
    {% for entry in entries %}
        <li class = "list-group-item">
            <h4>@{{ entry.accountname }}</h4>
            <form action="{{ url_for('vrconf.update_neverunfollow_entry') }}" method=post name = 'change_items' id="change_items">
                <input type=hidden value="{{ entry.id }}" name="id_to_delete" />
                <input type=hidden value="{{ entry.accountname }}" name="account_name" />
                <input type=submit value = "Change Entry" name="change"/>
                <input type=submit value = "Delete Entry" name="delete"/>
            </form>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <h2>Start entering never-to-delete account names</h2>
    {% endif %}
</div>
</div>

{% endblock %}

app/templates/vrconf/advanced_settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Valureach - Advanced Settings{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Enter Advanced Settings</h1>
</div>
<div class="col-md-4"> {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/vrconf/blacklist_settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Valureach - Negative Keywords and Blacklist Settings{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Enter Downweighted and Blacklisted Items</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form=form2, action=url_for('vrconf.blacklist_settings'))}}
</div>


<div class = "container">
<div class="col-md-12">
    <h1>Keyword List</h1>
    {% if entries|length > 0 %}
    <ul class= "list-group">
    {% for entry in entries %}
        <li class = "list-group-item">
            <h4>{{ entry.keyword }} ({{ entry.weight }}) </h4>
            <form action="{{ url_for('vrconf.update_blacklist_entry') }}" method=post name = 'change_items' id="change_items">
                <input type=hidden value="{{ entry.id }}" name="id_to_delete" />
                <input type=hidden value="{{ entry.keyword }}" name="keyword" />
                <input type=hidden value="{{ entry.weight }}" name="weight" />
                <input type=submit value = "Change Entry" name="change"/>
                <input type=submit value = "Delete Entry" name="delete"/>
            </form>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <h2>Start entering your keywords</h2>
    {% endif %}
</div>
</div>

{% endblock %}

app/templates/vrconf/connection_settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Valureach - Connection Settings{% endblock %}

{% block page_content %}

<h2>Initial Steps to be carried out on the Twitter website</h2>
<ul class = "list-group">
    <ui class = "list-group-item">login to your Twitter account</ui>
    <ui class = "list-group-item">make sure you have a mobile phone number assigned to your account</ui>
    <ui class = "list-group-item">go to apps.twitter.com</ui>
    <ui class = "list-group-item">create a new app, what you enter here is arbitrary</ui>
    <ui class = "list-group-item">create an access_token and access_token_secret</ui>
    <ui class = "list-group-item">enter these below with copy and paste</ui>
</ul>
<div class="page-header">
    <h1>Enter Connection Settings</h1>
</div>
<div class="col-md-4"> {{ wtf.quick_form(form) }}
</div>

{% endblock %}

app/templates/vrconf/delete_account.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Delete Your Valureach Account{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Are your sure?</h1>
</div>
<form action = "{{ url_for('vrconf.yes_delete')}}" method = POST>
<input type="submit" value = 'permanantly delete account' >
</form>
{% endblock %}

app/templates/vrconf/target_settings.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Valureach - Target Content Settings{% endblock %}

{% block page_content %}

<div class="page-header">
    <h1>Enter Target Content Settings</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form=form, action=url_for('vrconf.target_settings'))}}
</div>


<div class = "container">
<div class="col-md-12">
    <h1>Keyword List</h1>
    {% if entries|length > 0 %}
    <ul class= "list-group">
    {% for entry in entries %}
        <li class = "list-group-item">
            <h4>{{ entry.keyword }} ({{ entry.weight }}) </h4>
            <form action={{ url_for('vrconf.update_entry') }} method=post name = 'change_items' id="change_items">
                <input type=hidden value="{{ entry.id }}" name="id_to_delete" />
                <input type=hidden value="{{ entry.keyword }}" name="keyword" />
                <input type=hidden value="{{ entry.weight }}" name="weight" />
                <input type=submit value = "Change Entry" name="change"/>
                <input type=submit value = "Delete Entry" name="delete"/>
            </form>
        </li>
    {% endfor %}
    </ul>
    {% else %}
    <h2>Start entering your keywords</h2>
    {% endif %}
</div>
</div>

{% endblock %}